# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://www.oslobarnemuseum.no'
baseurl: ''
title: 'Oslo Barnemuseum'
description: 'Støtt barnas museum som permanent utstilling i Oslo gjennom å følge oss i sosiale medier.'
permalink: pretty
logo: "/assets/uploads/obmlogo.png"
date_format: %d.%m.%Y

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Hjem
  url: /
- title: Blogg
  url: /blog/
- title: Om
  url: /om/
- title: Kontakt
  url: /kontakt/

    # Footer nav
navigation_footer:
- title: Samskapt
  url: https://github.com/katieco/oslobarnemuseum
# Collections
collections:
  posts:
    title: Innlegg
    output: true
    description: "Oslo Barnemuseums blogg."
    feature_text: 
    feature_image: "/assets/uploads/zdenek-machacek-qctgjvk7qc8-unsplash.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

social_links:
  Twitter: https://twitter.com/oslobarnemuseum
  Facebook: https://www.facebook.com/oslobarnemuseum
  GitHub: https://github.com/katieco/oslobarnemuseum
  RSS: "/feed.xml"

