# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml
- gitpod.yml
- Dockerfile

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
timezone: Europe/Oslo
url: 'https://www.oslobarnemuseum.no'
baseurl: ''
title: 'Oslo Barnemuseum'
description: 'Støtt barnas egne permanent utstilling i Oslo ved å følge oss i sosiale medier. <a href="/om/">Les mer her.</a>'
permalink: pretty
logo: "/assets/uploads/obmlogo.png"
date_format: "%d.%m.%Y"

favicons: 
  16: '/assets/favicon.png'
  32: '/assets/favicon-32x32.png'



# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Hjem
  url: /
- title: Nyheter
  url: /blog/
- title: Om
  url: /om/
- title: Kontakt
  url: /kontakt/

    # Footer nav
navigation_footer:
- title: Samskapt
  url: https://github.com/lassegs/obm5
  
# Collections
collections:
  posts:
    title: Nyheter
    output: true
    description: "Oslo Barnemuseums blogg."
    feature_text: 
    feature_image: "/assets/uploads/zdenek-machacek-qctgjvk7qc8-unsplash.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

social_links:
  Twitter: https://twitter.com/oslobarnemuseum
  Facebook: https://www.facebook.com/oslobarnemuseum
  GitHub: https://github.com/katieco/oslobarnemuseum
  RSS: "/feed.xml"

